### ISSUE TITLE
wanted: rules_ruby

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-central-registry#1083]
### Module location

Various forks

### Any other context to provide?

[protobuf ](https://registry.bazel.build/modules/protobuf) is in the registry, but cannot be updated to a more recent release due to a newly introduced dependency on rules_ruby, see https://github.com/protocolbuffers/protobuf/issues/14569

Unfortunately rules_ruby has gone through a series of forks, and I don't think any of them are canonical.

- https://github.com/protocolbuffers/rules_ruby - this is what protobuf depends on, so the simplest answer is to put that in BCR
- https://github.com/coinbase/rules_ruby - ** Current Status:** Work in progress.
- https://github.com/bazelruby/rules_ruby forked from https://github.com/yugui/rules_ruby
- https://github.com/p0deje/rules_ruby used by Selenium team

The Rules Authors SIG has some funding now, so my sense is that we need to jump in front of this situation, determine which of these is the "canonical" and then put some effort into converging some of them again.

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by alexeagle** [comment]
As I announced on Bazel slack in `#ruby` we are planning to publish https://github.com/p0deje/rules_ruby  to BCR

**Comment by alexeagle** [comment]
https://registry.bazel.build/modules/rules_ruby

@p0deje yay!

**Comment by kigster** [comment]
Honestly, I think it might be helpful to get the bazelruby rules up to date and compare.

The focus when we wrote them was on staying as close as possible to a typical ruby developer flow. I don't know if we succeeded, but let's look at an example:

https://github.com/p0deje/rules_ruby/blob/main/examples/gem/spec/BUILD

Versus

https://github.com/bazelruby/rules_ruby/blob/master/examples/simple_script/BUILD.bazel#L53

The idea is that we don't want to create a BUILD file in each folder, and it's probably not desirable to have to have a target per test file. 

So my focus is on productivity and having Bazel co-exist with rhe ruby ecosystem, and definitely avoid requiring a BUILD file in every subdirectory of a spec folder or lib folder.

I want to make sure the examples from this  folder in rhe [bazelruby/rules_ruby](https://github.com/bazelruby/rules_ruby/tree/master/examples) still works with new rules. Otherwise porting projects would be a nightmare.

**Comment by p0deje** [comment]
> The idea is that we don't want to create a BUILD file in each folder, and it's probably not desirable to have to have a target per test file.

The ruleset supports both. 

You can create a single test target that will run all the specs and pass extra arguments to it like this:

```bazel
rb_test(
    name = "spec",
    srcs = glob(["spec/*.rb"],
    main = "@bundle//:bin/rspec",
    args = ["--format", "progress"],
    deps = ["@bundle"],
)
```

```bash
bazel test --test_arg="--fail-fast" :spec
```

This is more common in Ruby projects. However, you can also create a tree of build files nested in directories which is more common in Bazel with a target per each spec file. The benefits of this approach are:

1. better caching of test results (one dependency change invalidates results only for the tests having this dependency)
2. out-of-the-box parallelism since Bazel runs each target in a separate process
3. ability to run individual tests w/o `--test_arg` usage
4. ability to use `--flaky_test_attempts` to run spec files that fail with flakiness

I made a small video back for Selenium showing why per-test targets are useful - https://youtu.be/lqqXHEBvU0Y
