### ISSUE TITLE
wanted: websocketpp

### ISSUE THREAD

**Issue by pvarcholik** [bazelbuild/bazel-central-registry#3045]
### Module location

https://github.com/zaphoyd/websocketpp

### Any other context to provide?

WebSocket++ is a C++11 header-only library that supports various transport layers included Boost.Asio and stand-alone Asio. This needs to compile under C++11, but it appears that the bazel build is pulling the stand-alone Asio library and it contains C++17 features. If possible, I'd like a bazel module that allows the use of Boost::Asio instead of the stand-alone library.

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by hofbi** [comment]
Websocket in general is already available at https://registry.bazel.build/modules/websocketpp. However, it depends on https://registry.bazel.build/modules/asio/1.28.2 which uses some C++17 features. According to the [readme](https://github.com/zaphoyd/websocketpp?tab=readme-ov-file#websocket-082), we could replace standalone asio with [boost.asio](https://registry.bazel.build/modules/boost.asio).

Question to the maintainers (@meteorcloudy since you approved the PRs). Should we create a completely new module such as `websocket-boost` or just a new version such as `0.8.2.boost`?

**Comment by lalten** [comment]
The reason I touched asio was to bring https://github.com/mvukov/rules_ros2/pull/238 forward. rules_ros2 needs asio in Workspace and I adapted the Bzlmod version to be compatible so the repo can use the same implementation for both modes.

I've seen @keith use some neat tricks for Bzlmod curl to switch the TLS backend: https://github.com/bazelbuild/bazel-central-registry/blob/dee0784290930a1c6839d4fd99eed74c82ed4255/modules/curl/8.8.0/patches/add_build_file.patch#L302-L305
Possibly you could do something similar for WebSocket++ to switch between Boost Asio and Standalone Asio.

Cc also @wep21 who has contributed the most recent incarnation of Boost Bzlmods

**Comment by hofbi** [comment]
I came up with [this first draft](https://github.com/bazelbuild/bazel-central-registry/pull/3050)
