### ISSUE TITLE
Content of `MODULE.bazel` in the BCR

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel-central-registry#36]
I am working on porting a ruleset to Bazel modules that uses dev dependencies, e.g. to support the tests for the presubmit checks. I am not sure whether the `MODULE.bazel` checked into the BCR should

1. be identical to the one in the rulesets repo, including dev dependencies or
2. contain only the non-dev dependencies, as there are the only ones relevant for dependency resolution when loaded as a module.

Is there a functional difference between and if not, is one of the approaches recommended?

**Comment by meteorcloudy** [comment]
Dev dependencies are ignored during dependency resolution for all modules except for the root module. So there is no functional difference between those two approaches.

In addition, you can use [--ignore_dev_dependency](https://docs.bazel.build/versions/main/command-line-reference.html#flag--check_direct_dependencies) to disable dev dependencies of the root module, so that you can test the targets you want to expose to downstream will still work without fetching dev dependencies.

There is also [--check_direct_dependencies](https://docs.bazel.build/versions/main/command-line-reference.html#flag--check_direct_dependencies) flag which let you fail the dependency resolution when the resolved dependency is not what you declared in your MODULE.bazel file.

(Just realized I should probably name the first one as `--ignore_dev_dependencies` 😅)

**Comment by fmeum** [comment]
In that case I'll probably keep the dev dependencies at the end of my repo's `MODULE.bazel` and strip them from the copy I check in to the BCR. Thanks!
