### ISSUE TITLE
wanted: google/benchmark

### ISSUE THREAD

**Issue by jsharpe** [bazelbuild/bazel-central-registry#384]
### Module location

https://github.com/google/benchmark

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by macandy13** [comment]
I started the migration of this module to bzlmod, please get in touch if you are about to do the same.

**Comment by macandy13** [comment]
Quick update on the progress: The C++ parts of the google-benchmark library have been fully migrated to bzlmod, but the Python bindings part is still pending. The reason is that for it to be properly done, some prework in python_rules (https://github.com/bazelbuild/rules_python/issues/824) need to happen (mainly a way to detect the current Python toolchain in a target to select the right Python headers).

**Comment by macandy13** [comment]
Clarification to my comment above: In order to depend on google/benchmark using blzmod (in a C++ project), everything should be in place now.

The Python bindings migration is needed to build the `pywheel` packages for [google-benchmark](https://pypi.org/project/google-benchmark/), so it is more of an internal TODO than a necessity in my opinion.
